services:
  app:
    build:
      context: ./app
    container_name: fastapi_app
    networks:
      - app-network
    environment:
      - DISPLAY=:99
      - MONGODB_URL=mongodb://host.docker.internal:27017
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    ports:
      - "8000:8000"

networks:
  app-network:
    driver: bridge