services:
  app:
    build:
      context: ./app
    container_name: fastapi_app
    networks:
      - app-network
    environment:
      - DISPLAY=:99
      - MONGODB_URL=mongodb://host.docker.internal:27017
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    ports:
      - "8000:8000"

  # nginx:
  #   build:
  #     context: ./nginx
  #   container_name: nginx_server
  #   ports:
  #     - "80:80"  # Expose Nginx on port 80
  #   depends_on:
  #     - app
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge