services:
  - type: web
    name: fastapi-app
    env: docker
    plan: free
    dockerfilePath: ./app/Dockerfile
    envVars:
      - key: DISPLAY
        value: ":99"
      - key: MONGODB_URL
        value: "mongodb://host.docker.internal:27017"
    buildCommand: docker-compose build
    startCommand: docker-compose up
    ports:
      - port: 8000

  # Uncomment and configure the following section if you want to include Nginx
  # - type: web
  #   name: nginx-server
  #   env: docker
  #   plan: free
  #   dockerfilePath: ./nginx/Dockerfile
  #   dependsOn:
  #     - fastapi-app
  #   ports:
  #     - port: 80